charset_comment_filter = require("charset_comment_filter") --Unicode分区提示
core2022 = require("core2022_filter") --自定义字符集过滤（常用字集）
-- dz_ci = require("dz_ci_filter") --单字模式 这个别用，有问题的
number_translator = require("number")
lua_unicode_display_filter = require("unicode_display")  --Unicode编码提示
calculator_translator = require("calculator_translator")  --简易计算器
exe_processor = require("exe")  -- 网页启动器
shijian_translator = require("shijian2") -- 高级时间
local user_predict = require("user_predict") -- 上屏后预测模块
user_predict_processor = user_predict.P
user_predict_translator = user_predict.T
user_predict_filter = user_predict.F
