# SPDX-FileCopyrightText: 2015 - 2025 Rime community
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate char_words.lua from a Rime .dict.yaml file.

Extracts multi-character words, groups by prefix (1-5 CJK characters),
sorts by weight (descending), and outputs a Lua table.

Usage:
    python script/generate_char_words.py <input.dict.yaml> <output.lua> [--max-per-prefix N] [--max-prefix-len M]
"""

import argparse
import os


def is_cjk(cp):
    """Check if code point is in CJK ranges."""
    return (
        (0x4E00 <= cp <= 0x9FFF) or
        (0x3400 <= cp <= 0x4DBF) or
        (0x20000 <= cp <= 0x2A6DF) or
        (0x2A700 <= cp <= 0x2B73F) or
        (0x2B740 <= cp <= 0x2B81F) or
        (0x2B820 <= cp <= 0x2CEAF) or
        (0x2CEB0 <= cp <= 0x2EBEF) or
        (0x30000 <= cp <= 0x3134F) or
        (0x2EBF0 <= cp <= 0x2EE5F) or
        (0xF900 <= cp <= 0xFAFF) or
        (0x2F800 <= cp <= 0x2FA1F) or
        (0x2E80 <= cp <= 0x2EFF) or
        (0x2F00 <= cp <= 0x2FDF)
    )


def iter_cjk_chars(s):
    """Iterate over CJK characters in a string."""
    for ch in s:
        if is_cjk(ord(ch)):
            yield ch


def parse_dict_yaml(filepath):
    """Parse a Rime .dict.yaml file, return list of (word, weight) tuples."""
    entries = []
    in_body = False
    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.rstrip('\n\r')
            if line == '...':
                in_body = True
                continue
            if not in_body:
                continue
            if not line or line.startswith('#'):
                continue
            parts = line.split('\t')
            if len(parts) >= 2:
                word = parts[0]
                try:
                    weight = float(parts[1])
                except ValueError:
                    weight = 0.0
                if word:
                    entries.append((word, weight))
    return entries


def build_mapping(entries, max_per_prefix, max_prefix_len=5):
    """Group words by prefix (1-N CJK chars), keep top N by weight.

    Args:
        entries: list of (word, weight) tuples.
        max_per_prefix: max words per prefix.
        max_prefix_len: max prefix length in characters (default 5).

    Returns a dict: prefix_string → [full_word, ...]
    """
    # Collect unique weights per word per prefix
    raw = {}
    for i in range(1, max_prefix_len + 1):
        raw[i] = {}

    for word, weight in entries:
        cjk_chars = list(iter_cjk_chars(word))
        n = len(cjk_chars)
        if n < 2:
            continue

        # Check prefix characters are all CJK
        check_len = min(max_prefix_len, n - 1)
        all_cjk = all(is_cjk(ord(c)) for c in cjk_chars[:check_len])
        if not all_cjk:
            continue

        for k in range(1, min(max_prefix_len, n - 1) + 1):
            prefix = ''.join(cjk_chars[:k])
            if prefix not in raw[k]:
                raw[k][prefix] = {}
            if word not in raw[k][prefix] or weight > raw[k][prefix][word]:
                raw[k][prefix][word] = weight

    # Build final mapping (longer prefixes first for priority), limiting per prefix
    mapping = {}
    for k in range(max_prefix_len, 0, -1):
        for prefix in sorted(raw[k].keys()):
            sorted_words = sorted(raw[k][prefix].items(), key=lambda x: -x[1])
            words = [w for w, _ in sorted_words[:max_per_prefix]]
            mapping[prefix] = words

    return mapping


def generate_lua(mapping, output_path, input_name):
    """Write the Lua table file."""
    total_words = sum(len(words) for words in mapping.values())

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('-- SPDX-FileCopyrightText: 2015 - 2025 Rime community\n')
        f.write('-- SPDX-License-Identifier: GPL-3.0-or-later\n')
        f.write('-- Auto-generated by script/generate_char_words.py\n')
        f.write(f'-- Source: {input_name}\n')
        f.write('-- Maps CJK character prefix (1-5 chars) to common words starting with that prefix.\n')
        f.write('-- Used as fallback by user_predict.lua.\n')
        f.write('local M = {}\n')
        f.write('\n')
        for prefix in mapping:
            words = mapping[prefix]
            if not words:
                continue
            f.write(f'M[{repr(prefix)}] = {{\n')
            for w in words:
                f.write(f'  {repr(w)},\n')
            f.write('}\n')
            f.write('\n')
        f.write('return M\n')
        stats = []
        for i in range(1, 6):
            cnt = sum(1 for k in mapping if len(k) == i)
            if cnt:
                stats.append(f'P{i}:{cnt}')
        f.write(f'\n-- {" ".join(stats)} total_entries:{len(mapping)} total_words:{total_words}\n')


def main():
    parser = argparse.ArgumentParser(
        description='Generate char_words.lua from a Rime .dict.yaml file')
    parser.add_argument('input', help='Input .dict.yaml file')
    parser.add_argument('output', help='Output .lua file')
    parser.add_argument('--max-per-prefix', type=int, default=40,
                        help='Maximum words per prefix (default: 40)')
    parser.add_argument('--max-prefix-len', type=int, default=5,
                        help='Maximum prefix length in characters (default: 5)')
    args = parser.parse_args()

    print(f'Reading {args.input}...')
    entries = parse_dict_yaml(args.input)
    print(f'  Found {len(entries)} entries')

    mapping = build_mapping(entries, args.max_per_prefix, args.max_prefix_len)
    for i in range(1, args.max_prefix_len + 1):
        cnt = sum(1 for k in mapping if len(k) == i)
        if cnt:
            print(f'  P{i}:{cnt}', end='')
    print(f' total:{len(mapping)} prefixes')

    generate_lua(mapping, args.output, os.path.basename(args.input))
    total_words = sum(len(words) for words in mapping.values())
    print(f'  Wrote {total_words} word references to {args.output}')


if __name__ == '__main__':
    main()
