# SPDX-FileCopyrightText: 2015 - 2025 Rime community
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate char_words.lua from a Rime .dict.yaml file.

Extracts multi-character words, groups by first CJK character,
sorts by weight (descending), and outputs a Lua table.

Usage:
    python script/generate_char_words.py <input.dict.yaml> <output.lua> [--max-per-char N]
"""

import argparse
import os


def is_cjk(cp):
    """Check if code point is in CJK ranges."""
    return (
        (0x4E00 <= cp <= 0x9FFF) or
        (0x3400 <= cp <= 0x4DBF) or
        (0x20000 <= cp <= 0x2A6DF) or
        (0x2A700 <= cp <= 0x2B73F) or
        (0x2B740 <= cp <= 0x2B81F) or
        (0x2B820 <= cp <= 0x2CEAF) or
        (0x2CEB0 <= cp <= 0x2EBEF) or
        (0x30000 <= cp <= 0x3134F) or
        (0x2EBF0 <= cp <= 0x2EE5F) or
        (0xF900 <= cp <= 0xFAFF) or
        (0x2F800 <= cp <= 0x2FA1F) or
        (0x2E80 <= cp <= 0x2EFF) or
        (0x2F00 <= cp <= 0x2FDF)
    )


def parse_dict_yaml(filepath):
    """Parse a Rime .dict.yaml file, return list of (word, weight) tuples."""
    entries = []
    in_body = False
    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.rstrip('\n\r')
            if line == '...':
                in_body = True
                continue
            if not in_body:
                continue
            if not line or line.startswith('#'):
                continue
            parts = line.split('\t')
            if len(parts) >= 2:
                word = parts[0]
                try:
                    weight = float(parts[1])
                except ValueError:
                    weight = 0.0
                if word:
                    entries.append((word, weight))
    return entries


def build_mapping(entries, max_per_char):
    """Group words by first CJK character, keep top N by weight."""
    raw = {}
    for word, weight in entries:
        if len(word) < 2:
            continue
        first = word[0]
        if not is_cjk(ord(first)):
            continue
        if first not in raw:
            raw[first] = {}
        if word not in raw[first] or weight > raw[first][word]:
            raw[first][word] = weight

    mapping = {}
    for char in sorted(raw.keys()):
        sorted_words = sorted(raw[char].items(), key=lambda x: -x[1])
        mapping[char] = [w for w, _ in sorted_words[:max_per_char]]
    return mapping


def generate_lua(mapping, output_path, input_name):
    """Write the Lua table file."""
    total_words = sum(len(words) for words in mapping.values())

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('-- SPDX-FileCopyrightText: 2015 - 2025 Rime community\n')
        f.write('-- SPDX-License-Identifier: GPL-3.0-or-later\n')
        f.write('-- Auto-generated by script/generate_char_words.py\n')
        f.write(f'-- Source: {input_name}\n')
        f.write('-- Maps CJK characters to common words starting with that character.\n')
        f.write('-- Used as fallback by user_predict.lua.\n')
        f.write('local M = {}\n')
        f.write('\n')
        for char in mapping:
            words = mapping[char]
            if not words:
                continue
            f.write(f'M[{repr(char)}] = {{\n')
            for w in words:
                f.write(f'  {repr(w)},\n')
            f.write('}\n')
            f.write('\n')
        f.write('return M\n')
        f.write(f'\n-- Total characters: {len(mapping)}, total words: {total_words}\n')


def main():
    parser = argparse.ArgumentParser(
        description='Generate char_words.lua from a Rime .dict.yaml file')
    parser.add_argument('input', help='Input .dict.yaml file')
    parser.add_argument('output', help='Output .lua file')
    parser.add_argument('--max-per-char', type=int, default=40,
                        help='Maximum words per character (default: 40)')
    args = parser.parse_args()

    print(f'Reading {args.input}...')
    entries = parse_dict_yaml(args.input)
    print(f'  Found {len(entries)} entries')

    mapping = build_mapping(entries, args.max_per_char)
    print(f'  Grouped into {len(mapping)} CJK characters')

    generate_lua(mapping, args.output, os.path.basename(args.input))
    total_words = sum(len(words) for words in mapping.values())
    print(f'  Wrote {total_words} words to {args.output}')


if __name__ == '__main__':
    main()
